name: Flutter iOS Debugging Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-ios:
    name: Build and Test Flutter iOS App
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Specify your desired Flutter version

      # Step 3: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build iOS app
      - name: Build iOS app
        run: flutter build ios --debug
        env:
          CI: true

      # Step 5: Run Flutter tests
      - name: Run Flutter tests
        run: flutter test

      # Step 6: Optional - Lint code
      - name: Run Flutter analyze
        run: flutter analyze

      # Step 7: Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-debug-build
          path: build/ios/Debug-iphonesimulator
